version: "3"
services:
  koperasi-argo-mulyo:
    image: postgres:14
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - koperasi-argo-mulyo

volumes:
  koperasi-argo-mulyo:

networks:
  koperasi-argo-mulyo:
